module.exports = [
    { name: 'Ghost Face (Disney)', id: 'en_us_ghostface' },
    { name: 'Chewbacca (Disney)', id: 'en_us_chewbacca' },
    { name: 'C3PO (Disney)', id: 'en_us_c3po' },
    { name: 'Stitch (Disney)', id: 'en_us_stitch' },
    { name: 'Stormtrooper (Disney)', id: 'en_us_stormtrooper' },
    { name: 'Rocket (Disney)', id: 'en_us_rocket' },
    { name: 'English AU - Female', id: 'en_au_001' },
    { name: 'English AU - Male', id: 'en_au_002' },
    { name: 'English UK - Male 1', id: 'en_uk_001' },
    { name: 'English UK - Male 2', id: 'en_uk_003' },
    { name: 'English US - Female 1 (Int. 1)', id: 'en_us_001' },
    { name: 'English US - Female 1 (Int. 2)', id: 'en_us_002' },
    { name: 'English US - Male 1', id: 'en_us_006' },
    { name: 'English US - Male 2', id: 'en_us_007' },
    { name: 'English US - Male 3', id: 'en_us_009' },
    { name: 'English US - Male 4', id: 'en_us_010' },
    { name: 'French - Male 1', id: 'fr_001' },
    { name: 'French - Male 2', id: 'fr_002' },
    { name: 'German - Female', id: 'de_001' },
    { name: 'German - Male', id: 'de_002' },
    { name: 'Spanish - Male', id: 'es_002' },
    { name: 'Spanish MX - Male', id: 'es_mx_002' },
    { name: 'Portuguese BR - Female 1', id: 'br_001' },
    { name: 'Portuguese BR - Female 2', id: 'br_003' },
    { name: 'Portuguese BR - Female 3', id: 'br_004' },
    { name: 'Portuguese BR - Male', id: 'br_005' },
    { name: 'Indonesian - Female', id: 'id_001' },
    { name: 'Japanese - Female 1', id: 'jp_001' },
    { name: 'Japanese - Female 2', id: 'jp_003' },
    { name: 'Japanese - Female 3', id: 'jp_005' },
    { name: 'Japanese - Male', id: 'jp_006' },
    { name: 'Korean - Male 1', id: 'kr_002' },
    { name: 'Korean - Female', id: 'kr_003' },
    { name: 'Korean - Male 2', id: 'kr_004' },
]